services:
  netpretender:
    image: netpretender:latest
    container_name: pretender
    depends_on:
      - valkey
    environment:
      - REDIS_HOST=valkey
      - REDIS_PORT=6379
    ports:
      - "22:22"
    networks:
      - testnet

  valkey:
    image: valkey/valkey
    container_name: valkey
    ports:
      - "6379:6379"
    networks:
      - testnet
    command: ["valkey-server", "--loglevel", "verbose"]


networks:
  testnet:
    driver: bridge