# Maybe implement reserved variables? like $command to get the input command.

devices:
  - name: modem
    port: 22
    vars:
      deviceId: "modem1"
      state: "enabled"
    commands:
      - command: show interface npm
        response: showing interface
        delay: 1
      - command: show interfaces --all
        multiPartResponse:
          - "SHOWING INTERFACES"
          - "INTERFACE 1"
          - "INTERFACE 2"
          - "INTERFACE 3"
          - "INTERFACE 4"
        delay: 1
      - command: print interfaces --all
        responseFile: ./responses/show_interface_all.txt
        delay: 1
      - command: print interfaces ${var}
        response: showing variable interface
        allowed_values:
          - "hello"
          - "hey there"
          - "true"
  - name: modem2
    port: 23
    vars:
      deviceId: "modem2"
      state: "enabled"
    commands:
      - command: show interface npm
        response: showing interface
        delay: 1
      - command: show interfaces --all
        responseFile: ./responses/show_interface_all.txt
        delay: 1
      - command: print interfaces --all
        responseFile: ./responses/show_interface_all.txt
        delay: 1
      - command: print interfaces ${var}
        response: showing variable interface
        allowed_values:
          - "hello"
          - "hey there"
          - "false"